In [1]:
import numpy as np

In [3]:
a = [1,2,3,4,5,6,7,np.nan,8]

In [4]:
a

[1, 2, 3, 4, 5, 6, 7, nan, 8]

In [5]:
arr = np.array(a)

In [6]:
arr

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,  nan,   8.])

In [7]:
arr+2

array([  3.,   4.,   5.,   6.,   7.,   8.,   9.,  nan,  10.])

In [8]:
arr*2


array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  nan,  16.])

In [10]:
a = [[1,2,4],[5,6,7],[8,9,3]]

In [13]:
arr = np.array(a,dtype=float)

In [14]:
arr

array([[ 1.,  2.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9.,  3.]])

In [16]:
arr.astype(int)

array([[1, 2, 4],
       [5, 6, 7],
       [8, 9, 3]])

In [17]:
arr.astype(str)

array([['1.0', '2.0', '4.0'],
       ['5.0', '6.0', '7.0'],
       ['8.0', '9.0', '3.0']],
      dtype='<U32')

In [18]:
arr.tolist()

[[1.0, 2.0, 4.0], [5.0, 6.0, 7.0], [8.0, 9.0, 3.0]]

In [19]:
arr.shape

(3, 3)

In [22]:
arr.dtype

dtype('float64')

In [23]:
arr.size

9

In [24]:
arr.ndim

2

In [25]:
arr>4

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True, False]], dtype=bool)

In [26]:
arr[arr>4]

array([ 5.,  6.,  7.,  8.,  9.])

In [30]:
arr[::-1,]

array([[ 8.,  9.,  3.],
       [ 5.,  6.,  7.],
       [ 1.,  2.,  4.]])

In [31]:
arr

array([[ 1.,  2.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9.,  3.]])

In [32]:
arr[::-1,::-1]

array([[ 3.,  9.,  8.],
       [ 7.,  6.,  5.],
       [ 4.,  2.,  1.]])

In [33]:
arr[1,2] = np.nan
arr[2,2] = np.inf

In [34]:
arr

array([[  1.,   2.,   4.],
       [  5.,   6.,  nan],
       [  8.,   9.,  inf]])

In [35]:
num = np.isnan(arr) | np.isinf(arr)

In [37]:
arr[num] = 0

In [38]:
arr

array([[ 1.,  2.,  4.],
       [ 5.,  6.,  0.],
       [ 8.,  9.,  0.]])

In [41]:
arr.min()


0.0

In [42]:
arr.max()

9.0

In [43]:

arr.mean()

3.8888888888888888

In [50]:
np.amin(arr,axis=0) # Column wise

array([ 1.,  2.,  0.])

In [51]:
np.amin(arr,axis =1) # row wise 

array([ 1.,  0.,  0.])

In [52]:
arr2 = arr

In [53]:
arr2[1,2] = 100

In [54]:
arr

array([[   1.,    2.,    4.],
       [   5.,    6.,  100.],
       [   8.,    9.,    0.]])

In [58]:
arr2 = arr[:,:].copy

In [66]:
arr.reshape(9,1)

array([[   1.],
       [   2.],
       [   4.],
       [   5.],
       [   6.],
       [ 100.],
       [   8.],
       [   9.],
       [   0.]])

In [67]:
arr

array([[   1.,    2.,    4.],
       [   5.,    6.,  100.],
       [   8.,    9.,    0.]])

In [68]:
b2 = arr.flatten()

In [69]:
b2

array([   1.,    2.,    4.,    5.,    6.,  100.,    8.,    9.,    0.])

In [70]:
b2.ravel()

array([   1.,    2.,    4.,    5.,    6.,  100.,    8.,    9.,    0.])

In [73]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [76]:
np.linspace(start = 0 ,stop = 50,num = 30,dtype = int)

array([ 0,  1,  3,  5,  6,  8, 10, 12, 13, 15, 17, 18, 20, 22, 24, 25, 27,
       29, 31, 32, 34, 36, 37, 39, 41, 43, 44, 46, 48, 50])

In [79]:
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [80]:
np.ones([4,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [81]:
uniqs, counts = np.unique(arr, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [   0.    1.    2.    4.    5.    6.    8.    9.  100.]
Counts       :  [1 1 1 1 1 1 1 1 1]
